services:

  menu-service:
    build: menu-service
    ports:
      - "8081:8081"
    env_file:
      - menu-service/.env
    depends_on:
      - menu-db
      - elasticsearch

  menu-db:
    image: postgres:16
    restart: always
    shm_size: 50mb
    container_name: menu-db
    ports:
      - "5440:5440"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - cluster.name=demo-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: always

  logstash:
    image: docker.elastic.co/logstash/logstash:8.17.2
    container_name: logstash
    environment:
      - LS_JAVA_OPTS=-Xmx256m -Xms256m
    volumes:
      - ./logstash/config:/logstash/logstash.config
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch
    restart: always






