spring:
  application:
    name: clientservice
  profiles:
    active: ${ENV}
  mvc:
    log-request-details: true

logging:
  level:
    org:
      springframework:
        web: DEBUG

elasticsearch:
  connection.url: elasticsearch:9200