services:
  menu-service:
    deploy:
      resources:
        limits:
          memory: 1000M
    container_name: menu-service
    build:
      context: ../menu-service
      dockerfile: ../menu-service/Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - ../menu-service/.env
    networks:
      - elk
    depends_on:
      - database
      - elasticsearch
      - logstash
    links:
      - database
      - logstash

  client-service:
    deploy:
      resources:
        limits:
          memory: 1000M
    container_name: client-service
    build:
      context: ../clientservice
      dockerfile: ../clientservice/Dockerfile
    ports:
      - "8082:8082"
    env_file:
      - ../clientservice/.env
    networks:
      - elk
    depends_on:
      - database
      - elasticsearch
      - logstash
    links:
      - database
      - logstash

  database:
    deploy:
      resources:
        limits:
          memory: 3000M
    image: postgres:16
    restart: always
    shm_size: 50mb
    container_name: database
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ../menu-service/.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER $POSTGRES_DB" ]
      interval: 5s
      retries: 5
      timeout: 3s
    networks:
      - elk
    hostname: database


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.audit.enabled=true
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elk
    hostname: elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
    deploy:
      resources:
        limits:
          memory: 1000M
    hostname: kibana

  logstash:
    image: docker.elastic.co/logstash/logstash:8.17.2
    container_name: logstash
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - ./logstash/config/logstash.conf:/usr/share/logstash/config/logstash.conf:ro
    networks:
      - elk
    ports:
      - "9600:9600"
      - "5000:5000"
    depends_on:
      - elasticsearch
    deploy:
      resources:
        limits:
          memory: 1000M
    hostname: logstash

volumes:
  elasticsearch-data:
    driver: local

networks:
  elk:
    driver: bridge